Update savgol_filter to include deriv functionality
qsib-cbie/sci-rs pull request #54
Opened 2024-10-21 20:15 UTC by jkv64

This expands the functionality of the savgol_filter_dyn method to include the differentiation capability that the original [sci_py method](https://github.com/scipy/scipy/blob/main/scipy/signal/_savitzky_golay.py#L8-L144) has. This addition allows for the possibility of taking a derivative of a signal as it is convolved with the Savitsky-Golay filter. The [Wikipedia page](https://en.m.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter) has a good summary of the math involved, along with high quality visualizations.

This update also includes several more unit tests for the savgol_filter_dyn and savgol_coeffs_dyn methods and fixes an off by one error in the padding before convolution of savgol_filter_dyn.

A demonstration of different numbers of derivatives for fixed input is given below.
![image](https://github.com/user-attachments/assets/b251e193-d398-424a-b765-3e5519a11bda)

I'm looking for confirmation that everything seems documented properly, since this is my first addition to sci-rs. Let me know what you think @trueb2

2024-11-04 15:42 UTC, trueb2 requested changes
Thanks for the contribution. Looks like things are working but need to be cleaned up a bit.

2024-11-04 15:42 UTC, trueb2 commented on sci-rs/src/signal/filter/savgol_filter.rs
>  #[cfg(feature = "alloc")]
Imports related to testing should only be included in the test mods. That would be moving imports into the 
```rust
#[cfg(test)]
mod tests {
  use super::*; //  just for import crate stuff, not test deps

  ...

}
```

Separately, I don't think we want tests that edit the file system, so these imports will be unnecessary.

2024-11-04 15:42 UTC, trueb2 commented on sci-rs/src/signal/filter/savgol_filter.rs
> +) -> Vec<F>
Here and for savgol_filter_dyn, we should accept parameters that make it clear what the defaults are like the kwargs. For example, deriv would be an Option<usize> that you would unwrap_or(0) and delta would be an Option<F> that you would unwrap or F::one()

2024-11-04 15:42 UTC, trueb2 commented on sci-rs/src/signal/filter/savgol_filter.rs
> +        }
We should remove this test

2024-11-05 21:28 UTC, jkv64 commented
@trueb2 Thanks for the feedback! The changes should all be incorporated now.

2024-11-12 15:27 UTC, trueb2 commented
This looks good. Thanks for your contribution!

When this merges, the next release will need to bump the minor version since this includes some interface change.

2024-11-12 15:27 UTC, trueb2 approved these changes

2024-11-12 15:28 UTC, merged